message(STATUS "[PlayRho] Resolving external dependency")

# Define PlayRho version
set(PLAYRHO_VERSION 0.9.0)
set(PLAYRHO_DIR PlayRho)

include(ExternalPlayRho)

list(APPEND EXTERNAL_DEPENDENCIES ${PLAYRHO_TARGETS})
list(APPEND EXTERNAL_LIBRARY_DIRS ${PLAYRHO_LIBRARY_DIRS})
list(APPEND EXTERNAL_INCLUDE_DIRS ${PLAYRHO_INCLUDE_DIRS})
list(APPEND EXTERNAL_LIBRARIES ${PLAYRHO_LIBRARIES})

message(STATUS "[PlayRho] Using ${PLAYRHO_VERSION}")
