# Source files
file(GLOB_RECURSE INTERNAL_SOURCE_FILES "${PROJECT_SOURCE_DIR}/${SOURCE_DIR}/*pp")
file(GLOB_RECURSE TEST_FILES "${PROJECT_SOURCE_DIR}/${TEST_DIR}/*pp")

list(APPEND SOURCE_FILES ${INTERNAL_SOURCE_FILES} ${TEST_FILES})
